### ISSUE TITLE
[1.7.10] Ticking memory connection  java.util.NoSuchElementException: None.get

### ISSUE THREAD

**Issue by asederf** [Chicken-Bones/ForgeMultipart#338]
When i place Universal cable, logistical pipe or pressurized tube from mekanism mod, I get this crash report:

---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 31.05.2015 20:40
Description: Ticking memory connection

java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:322)
	at scala.None$.get(Option.scala:320)
	at codechicken.multipart.MultiPartRegistry$.writePartID(MultiPartRegistry.scala:191)
	at codechicken.multipart.TileMultipart.writeAddPart(TileMultipart.scala:289)
	at codechicken.multipart.TileMultipart.addPart_impl(TileMultipart.scala:275)
	at codechicken.multipart.MultipartGenerator$.addPart(MultipartGenerator.scala:97)
	at codechicken.multipart.TileMultipart$.addPart(TileMultipart.scala:601)
	at codechicken.multipart.TItemMultiPart$class.place$1(ItemMultiPart.scala:37)
	at codechicken.multipart.TItemMultiPart$class.onItemUse(ItemMultiPart.scala:47)
	at codechicken.multipart.JItemMultiPart.func_77648_a(ItemMultiPart.scala:14)
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505)
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:128)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:389)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by asederf** [comment]
Cant someone fix this ?

**Comment by TheJulianJES** [comment]
1. Update Mekanism
2. Update ForgeMultipart
3. If this is not fixed, create an issue on the Mekanism tracker.

**Comment by asederf** [comment]
I updated both, but my problem didnt fix. I created an issue on mekanism tracker too but they told me that it is a Forge multipart crash.

**Comment by RAWRwins254** [comment]
@TheJulianJES from what I can see, It could be version mismatches in a slightly different case of this crash. I don't believe it's mekanism causing this crash. The report that I found posted on mekanism's tracker was/is (I suspect anyways) version mismatches of CCL and CCC causing an interference. I know friends of mine who just download the mod versions listed on the "front" page for their MC version and don't think that maybe there's something newer. This in and of itself is where I see most of the FMP/CCC/CCL issues arise from. People using 1.0.4.29 of CCC instead of the mekanism-built-in version that is 1.0.6.39. I personally use 1.0.7.45 of CCC for my server.
