### ISSUE TITLE
TileEntity missing mapping | FMP 345

### ISSUE THREAD

**Issue by NitroxydeX** [Chicken-Bones/ForgeMultipart#345]
Console Spam Multiple Times

```
[23:09:31] [Server thread/ERROR] [FML]: A TileEntity type codechicken.multipart.handler.MultipartSaveLoad$TileNBTContainer has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.RuntimeException: class codechicken.multipart.handler.MultipartSaveLoad$TileNBTContainer is missing a mapping! This is a bug!
        at net.minecraft.tileentity.TileEntity.func_145841_b(TileEntity.java:80) ~[aor.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:370) [aqk.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:197) [aqk.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:256) [ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:302) [ms.class:?]
        at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:809) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:318) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:569) [MinecraftServer.class:?]
        at fastcraft.c.p.a(F:19) [fastcraft-1.22-ttest.jar:?]
        at fastcraft.Hooks.aq(F:153) [fastcraft-1.22-ttest.jar:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

**Comment by goreacraft** [comment]
Same issue here...
Server running with KCauldron-1.7.10-1448.121-server.jar and modpack FTB Infinity 1.6.2

Error:
.06 19:28:16 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40-internal]
20.06 19:28:16 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
20.06 19:28:16 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:834) [MinecraftServer.class:?]
20.06 19:28:16 [Server] INFO at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:530) [MinecraftServer.class:?]
20.06 19:28:16 [Server] INFO at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1051) [mt.class:?]
20.06 19:28:16 [Server] INFO at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:439) [ms.class:?]
20.06 19:28:16 [Server] INFO at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:359) [ms.class:?]
20.06 19:28:16 [Server] INFO at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:218) [aqk.class:?]
20.06 19:28:16 [Server] INFO at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:391) [aqk.class:?]
20.06 19:28:16 [Server] INFO at net.minecraft.tileentity.TileEntity.func_145841_b(TileEntity.java:84) ~[aor.class:?]
20.06 19:28:16 [Server] INFO java.lang.RuntimeException: class codechicken.multipart.handler.MultipartSaveLoad$TileNBTContainer is missing a mapping! This is a bug!
20.06 19:28:16 [Server] ERROR A TileEntity type codechicken.multipart.handler.MultipartSaveLoad$TileNBTContainer has throw an exception trying to write state. It will not persist. Report this to the mod author

**Comment by trismegistis** [comment]
Same issue here.

openeye.logic.ThrowableLogger.processThrowable(ThrowableLogger.java:84): Limit reached for location tile_entity_write

**Comment by Redlotus99** [comment]
I've got the same issue also.

**Comment by iccle** [comment]
I have the same issue using forgeMultipart-1.7.10-1.2.0.344-universal.jar

If any block which contains microblocks is copied/pasted/stacked/moved using worldedit it leaves behind ghost entities in the spaces where the microblocks were, any attempt to place another block into this space will disconnect you from the server, the only solution i have found thus far is to //undo any modifications and remove the microblocks manually.

**Comment by iccle** [comment]
I have just updated to the following:
CodeChickenCore-1.7.10-1.0.7.47-universal.jar
ForgeMultipart-1.7.10-1.2.0.345-universal.jar
NotEnoughItems-1.7.10-1.0.5.118-universal.jar (was required when i attempted to start with the previous two updates)

This crash still persists in the latest dev versions:
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 23/11/15 18:58
Description: Ticking memory connection

java.lang.RuntimeException: class codechicken.multipart.handler.MultipartSaveLoad$TileNBTContainer is missing a mapping! This is a bug!
	at net.minecraft.tileentity.TileEntity.func_145841_b(TileEntity.java:80)
	at net.minecraftforge.common.util.BlockSnapshot.<init>(BlockSnapshot.java:52)
	at net.minecraftforge.common.util.BlockSnapshot.<init>(BlockSnapshot.java:81)
	at net.minecraftforge.common.util.BlockSnapshot.getBlockSnapshot(BlockSnapshot.java:107)
	at net.minecraft.world.World.func_147465_d(World.java:447)
	at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:206)
	at net.minecraft.item.ItemBlock.func_77648_a(ItemBlock.java:103)
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505)
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:128)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:389)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.tileentity.TileEntity.func_145841_b(TileEntity.java:80)
	at net.minecraftforge.common.util.BlockSnapshot.<init>(BlockSnapshot.java:52)
	at net.minecraftforge.common.util.BlockSnapshot.<init>(BlockSnapshot.java:81)
	at net.minecraftforge.common.util.BlockSnapshot.getBlockSnapshot(BlockSnapshot.java:107)
	at net.minecraft.world.World.func_147465_d(World.java:447)
	at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:206)
	at net.minecraft.item.ItemBlock.func_77648_a(ItemBlock.java:103)
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505)
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:128)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:389)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@2e7807e6
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 376982048 bytes (359 MB) / 967090176 bytes (922 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 39 mods loaded, 39 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
	UCHIJAAAA	OpenComputers|Core{1.5.20.38} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJAAAA	OpenModsCore{0.8} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0-102.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
	UCHIJAAAA	BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) 
	UCHIJAAAA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1067-universal.jar) 
	UCHIJAAAA	BuildCraft|Core{7.1.13} [BuildCraft] (buildcraft-7.1.13.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.1.13} [BC Builders] (buildcraft-7.1.13.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.1.13} [BC Transport] (buildcraft-7.1.13.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.1.13} [BC Energy] (buildcraft-7.1.13.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.1.13} [BC Silicon] (buildcraft-7.1.13.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.1.13} [BC Robotics] (buildcraft-7.1.13.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.1.13} [BC Factory] (buildcraft-7.1.13.jar) 
	UCHIJAAAA	BuildCraft|Compat{7.1.2} [BuildCraft Compat] (buildcraft-compat-7.1.2.jar) 
	UCHIJAAAA	endercore{1.7.10-0.1.0.24_beta} [EnderCore] (EnderCore-1.7.10-0.1.0.24_beta.jar) 
	UCHIJAAAA	EnderIO{1.7.10-2.2.8.381} [Ender IO] (EnderIO-1.7.10-2.2.8.381.jar) 
	UCHIJAAAA	EnderStorage{1.4.7.37} [EnderStorage] (EnderStorage-1.7.10-1.4.7.37-universal.jar) 
	UCHIJAAAA	enhancedportals{3.0.12} [EnhancedPortals] (EnhancedPortals_1.7.10-universal-3.0.12.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	inventorytweaks{1.59-dev-156-af3bc68} [Inventory Tweaks] (InventoryTweaks-1.59-dev-156.jar) 
	UCHIJAAAA	IronChest{6.0.60.741} [Iron Chest] (Ironchest-1.7.10-6.0.60.741-universal.jar) 
	UCHIJAAAA	journeymap{5.1.1b9} [JourneyMap] (journeymap-1.7.10-5.1.1b9-unlimited.jar) 
	UCHIJAAAA	LogisticsPipes{0.9.3.69} [Logistics Pipes] (logisticspipes-0.9.3.69.jar) 
	UCHIJAAAA	OpenComputers{1.5.20.38} [OpenComputers] (OpenComputers-MC1.7.10-1.5.20.38-universal.jar) 
	UCHIJAAAA	OpenMods{0.8} [OpenMods] (OpenModsLib-1.7.10-0.8.jar) 
	UCHIJAAAA	Railcraft{9.8.0.0} [Railcraft] (Railcraft_1.7.10-9.8.0.0.jar) 
	UCHIJAAAA	ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.1.0-161.jar) 
	UCHIJAAAA	worldedit{6.0-beta-01} [WorldEdit] (worldedit-forge-mc1.7.10-6.0-beta-01.jar) 
	UCHIJAAAA	zettaindustries{1.1} [Zetta Industries] (zettaindustries-1.1-97.jar) 
	UCHIJAAAA	aobd{2.8.4} [Another One Bites The Dust] (AOBD-2.8.4.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: all safe
	CoFHCore: -[1.7.10]3.0.3-303
	ThermalFoundation: -[1.7.10]1.2.0-102
	ThermalExpansion: -[1.7.10]4.0.3B1-218
	ThermalDynamics: -[1.7.10]1.1.0-161
	Stencil buffer state: Function set: GL30, pool: forge, bits: 8
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['iccle'/114, l='New World', x=-20.65, y=70.00, z=231.29]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by timvandenhof** [comment]
Is there any update on this issue? Experiencing this same issue when copy-pasting structures that contains forge multipart items. Using world edit for copy-paste.

Forge: forge-1.7.10-10.13.4.1614-1.7.10-universal
FMP: ForgeMultipart-1.7.10-1.2.0.345-universal
CCC: CodeChickenCore-1.7.10-1.0.7.47-universal
WE: worldedit-forge-mc1.7.10-6.1.1-SNAPSHOT-dist

**Comment by NitroxydeX** [comment]
ForgeMultipart is dead. It's now named MCMultiPart and is maintained by someone else: https://github.com/amadornes/MCMultiPart

So likely this issue will never be fixed. Mekanism now uses MCMultiPart for Example. For better building in 1.10 and above you should use "Chisel & Bits" mod.

**Comment by simon816** [comment]
ForgeMultipart is now maintained by TheCBProject: https://github.com/TheCBProject/ForgeMultipart

**Comment by trismegistis** [comment]
way too old anyway use spongeforge 1.11~ now
