### ISSUE TITLE
Crash when i take Acacia wood planks strip. :"(

### ISSUE THREAD

**Issue by MoonDroper** [Chicken-Bones/ForgeMultipart#358]
[19:16:53] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 23.7.15 19:16
Description: Unexpected error

java.lang.AbstractMethodError: mrtjp.projectred.transmission.JacketedHighlightRenderer$.renderHighlight(Lnet/minecraft/entity/player/EntityPlayer;Lnet/minecraft/util/MovingObjectPosition;Lcodechicken/microblock/CommonMicroClass;II)Z
	at codechicken.microblock.MicroMaterialRegistry$$anonfun$2.apply(MicroMaterialRegistry.scala:233)
	at codechicken.microblock.MicroMaterialRegistry$$anonfun$2.apply(MicroMaterialRegistry.scala:233)
	at scala.collection.LinearSeqOptimized$class.find(LinearSeqOptimized.scala:99)
	at scala.collection.immutable.List.find(List.scala:83)
	at scala.collection.generic.TraversableForwarder$class.find(TraversableForwarder.scala:43)
	at scala.collection.mutable.ListBuffer.find(ListBuffer.scala:45)
	at codechicken.microblock.MicroMaterialRegistry$.renderHighlight(MicroMaterialRegistry.scala:233)
	at codechicken.microblock.ItemMicroPartRenderer$.renderHighlight(ItemMicroPart.scala:168)
	at codechicken.microblock.handler.MicroblockEventHandler$.drawBlockHighlight(MicroblockEventHandler.scala:35)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_317_MicroblockEventHandler$_drawBlockHighlight_DrawBlockHighlightEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:256)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1254)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at codechicken.microblock.MicroMaterialRegistry$$anonfun$2.apply(MicroMaterialRegistry.scala:233)
	at codechicken.microblock.MicroMaterialRegistry$$anonfun$2.apply(MicroMaterialRegistry.scala:233)
	at scala.collection.LinearSeqOptimized$class.find(LinearSeqOptimized.scala:99)
	at scala.collection.immutable.List.find(List.scala:83)
	at scala.collection.generic.TraversableForwarder$class.find(TraversableForwarder.scala:43)
	at scala.collection.mutable.ListBuffer.find(ListBuffer.scala:45)
	at codechicken.microblock.MicroMaterialRegistry$.renderHighlight(MicroMaterialRegistry.scala:233)
	at codechicken.microblock.ItemMicroPartRenderer$.renderHighlight(ItemMicroPart.scala:168)
	at codechicken.microblock.handler.MicroblockEventHandler$.drawBlockHighlight(MicroblockEventHandler.scala:35)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_317_MicroblockEventHandler$_drawBlockHighlight_DrawBlockHighlightEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:256)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1254)

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityClientPlayerMP['MoonDroper'/166928, l='MpServer', x=-335,93, y=62,62, z=554,03], EntityOtherPlayerMP['Rosiq'/255, l='MpServer', x=-303,59, y=73,00, z=706,72]]
	Chunk stats: MultiplayerChunkCache: 930, 930
	Level seed: 0
	Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (168,64,1024), Chunk: (at 8,4,0 in 10,64; contains blocks 160,0,1024 to 175,255,1039), Region: (0,2; contains chunks 0,64 to 31,95, blocks 0,0,1024 to 511,255,1535)
	Level time: 11641386 game time, 11950838 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 100 total; [EntityItem['item.item.egg'/165644, l='MpServer', x=-388,25, y=73,13, z=539,28], EntitySpider['Spider'/168717, l='MpServer', x=-393,53, y=96,00, z=581,84], EntityClientPlayerMP['MoonDroper'/166928, l='MpServer', x=-335,93, y=62,62, z=554,03], EntityZombie['Zombie'/167962, l='MpServer', x=-405,50, y=30,00, z=594,75], EntityZombie['Zombie'/167963, l='MpServer', x=-400,50, y=28,00, z=598,50], EntitySkeleton['Skeleton'/168219, l='MpServer', x=-291,50, y=67,00, z=481,50], EntitySkeleton['Skeleton'/167960, l='MpServer', x=-395,50, y=28,00, z=595,50], EntitySkeleton['Skeleton'/168220, l='MpServer', x=-289,84, y=67,00, z=482,50], EntityBat['Bat'/167480, l='MpServer', x=-358,69, y=44,51, z=616,75], EntityChicken['Chicken'/63, l='MpServer', x=-366,47, y=72,00, z=523,56], EntityLocomotiveSteamSolid['Steam Locomotive'/65, l='MpServer', x=-327,06, y=60,50, z=559,50], EntityCartTank['Tank Cart'/66, l='MpServer', x=-328,69, y=60,50, z=559,50], EntityCartBasic['entity.MinecartRideable.name'/67, l='MpServer', x=-330,28, y=60,50, z=559,50], EntityChicken['Chicken'/68, l='MpServer', x=-295,56, y=69,00, z=532,53], EntitySheep['Sheep'/69, l='MpServer', x=-266,47, y=68,00, z=512,22], EntitySheep['Sheep'/72, l='MpServer', x=-256,19, y=64,00, z=543,34], EntityCreeper['Creeper'/165966, l='MpServer', x=-362,31, y=13,00, z=632,16], EntityCreeper['Creeper'/167245, l='MpServer', x=-377,31, y=13,00, z=558,84], EntitySkeleton['Skeleton'/167506, l='MpServer', x=-378,50, y=13,00, z=592,50], EntitySkeleton['Skeleton'/167248, l='MpServer', x=-373,50, y=13,00, z=555,50], EntitySkeleton['Skeleton'/167249, l='MpServer', x=-373,50, y=13,00, z=551,50], EntitySkeleton['Skeleton'/167505, l='MpServer', x=-379,50, y=13,00, z=592,50], EntityHorse['Donkey'/83, l='MpServer', x=-400,22, y=73,00, z=526,13], EntityChicken['Chicken'/87, l='MpServer', x=-391,47, y=74,00, z=540,53], EntitySheep['Sheep'/90, l='MpServer', x=-329,97, y=70,00, z=502,03], EntityBat['Bat'/168793, l='MpServer', x=-316,52, y=39,00, z=592,71], EntitySheep['Sheep'/93, l='MpServer', x=-361,94, y=75,00, z=614,09], EntitySheep['Sheep'/94, l='MpServer', x=-366,91, y=75,00, z=616,53], EntitySheep['Sheep'/95, l='MpServer', x=-358,09, y=75,00, z=620,53], EntitySheep['Sheep'/96, l='MpServer', x=-364,47, y=75,00, z=615,28], EntityBat['Bat'/168802, l='MpServer', x=-354,44, y=27,84, z=601,47], EntityZombie['Zombie'/167523, l='MpServer', x=-296,88, y=50,00, z=624,78], EntitySheep['Sheep'/97, l='MpServer', x=-364,47, y=75,00, z=617,41], EntityBat['Bat'/167011, l='MpServer', x=-342,25, y=15,10, z=608,91], EntitySheep['Sheep'/98, l='MpServer', x=-358,34, y=75,00, z=618,78], EntityBat['Bat'/168800, l='MpServer', x=-347,92, y=21,87, z=610,77], EntitySheep['Sheep'/99, l='MpServer', x=-360,97, y=75,00, z=619,50], EntityBat['Bat'/168801, l='MpServer', x=-355,49, y=27,59, z=609,74], EntitySheep['Sheep'/100, l='MpServer', x=-364,34, y=75,00, z=614,09], EntitySheep['Sheep'/101, l='MpServer', x=-365,63, y=75,00, z=615,22], EntityZombie['Zombie'/167524, l='MpServer', x=-300,97, y=54,00, z=621,50], EntitySheep['Sheep'/102, l='MpServer', x=-360,72, y=75,00, z=614,09], EntitySheep['Sheep'/103, l='MpServer', x=-363,41, y=75,00, z=618,59], EntitySheep['Sheep'/104, l='MpServer', x=-358,38, y=75,00, z=614,09], EntitySkeleton['Skeleton'/168554, l='MpServer', x=-323,50, y=70,00, z=507,50], EntitySheep['Sheep'/105, l='MpServer', x=-358,19, y=75,00, z=615,25], EntitySheep['Sheep'/106, l='MpServer', x=-361,03, y=75,00, z=618,06], EntitySheep['Sheep'/107, l='MpServer', x=-366,91, y=75,00, z=615,25], EntitySheep['Sheep'/108, l='MpServer', x=-365,72, y=75,00, z=614,09], EntitySheep['Sheep'/109, l='MpServer', x=-365,53, y=75,00, z=618,53], EntitySheep['Sheep'/110, l='MpServer', x=-359,53, y=75,00, z=614,63], EntitySheep['Sheep'/111, l='MpServer', x=-362,19, y=75,00, z=619,31], EntitySheep['Sheep'/112, l='MpServer', x=-366,91, y=75,00, z=614,09], EntitySheep['Sheep'/113, l='MpServer', x=-365,69, y=75,00, z=616,47], EntityHorse['Horse'/114, l='MpServer', x=-353,44, y=75,80, z=613,28], EntityBat['Bat'/169328, l='MpServer', x=-299,41, y=38,41, z=616,28], EntitySquid['Squid'/168834, l='MpServer', x=-367,50, y=50,16, z=526,72], EntitySheep['Sheep'/129, l='MpServer', x=-281,25, y=69,00, z=526,19], EntitySquid['Squid'/168835, l='MpServer', x=-372,50, y=51,00, z=526,63], EntitySquid['Squid'/168836, l='MpServer', x=-370,25, y=51,38, z=525,56], EntitySquid['Squid'/168837, l='MpServer', x=-371,53, y=51,00, z=525,53], EntityBat['Bat'/167817, l='MpServer', x=-276,91, y=15,89, z=605,53], EntitySpider['Spider'/167564, l='MpServer', x=-385,47, y=74,00, z=496,22], EntitySpider['Spider'/162963, l='MpServer', x=-257,84, y=70,00, z=593,53], EntityBat['Bat'/168080, l='MpServer', x=-276,59, y=34,00, z=514,97], EntityCreeper['Creeper'/168596, l='MpServer', x=-272,50, y=54,00, z=612,50], EntityItem['item.item.egg'/161691, l='MpServer', x=-366,56, y=72,13, z=526,13], EntityCreeper['Creeper'/167577, l='MpServer', x=-256,50, y=67,00, z=486,50], EntitySheep['Sheep'/21409, l='MpServer', x=-360,84, y=75,00, z=615,22], EntitySheep['Sheep'/167, l='MpServer', x=-381,47, y=65,00, z=475,53], EntityHorse['Horse'/170, l='MpServer', x=-284,84, y=68,00, z=509,03], EntitySheep['Sheep'/171, l='MpServer', x=-294,06, y=67,00, z=489,91], EntityWitch['Witch'/169135, l='MpServer', x=-262,50, y=29,00, z=488,50], EntityLeashKnot['entity.LeashKnot.name'/174, l='MpServer', x=-350,50, y=75,50, z=615,50], EntityZombie['Zombie'/168877, l='MpServer', x=-265,25, y=68,00, z=518,50], EntityCreeper['Creeper'/169136, l='MpServer', x=-266,91, y=29,14, z=489,50], EntityBat['Bat'/169402, l='MpServer', x=-367,25, y=13,02, z=564,25], EntityCreeper['Creeper'/163771, l='MpServer', x=-369,50, y=13,00, z=626,50], EntityBat['Bat'/169403, l='MpServer', x=-364,50, y=13,26, z=560,53], EntityBat['Bat'/169401, l='MpServer', x=-373,06, y=14,45, z=572,91], EntityBat['Bat'/169406, l='MpServer', x=-369,75, y=13,26, z=559,41], EntityOtherPlayerMP['Rosiq'/255, l='MpServer', x=-303,59, y=73,00, z=706,72], EntityBat['Bat'/169404, l='MpServer', x=-367,25, y=13,00, z=572,22], EntityBat['Bat'/169405, l='MpServer', x=-369,75, y=14,85, z=569,56], EntityCreeper['Creeper'/167107, l='MpServer', x=-345,50, y=35,00, z=599,50], EntitySpider['Spider'/167105, l='MpServer', x=-399,66, y=74,00, z=532,34], EntityBat['Bat'/169418, l='MpServer', x=-347,25, y=48,45, z=507,47], EntityBat['Bat'/167887, l='MpServer', x=-374,34, y=49,10, z=575,69], EntityBat['Bat'/169420, l='MpServer', x=-348,38, y=47,92, z=509,50], EntityZombie['Zombie'/166613, l='MpServer', x=-294,50, y=76,00, z=624,50], EntitySquid['Squid'/169191, l='MpServer', x=-370,49, y=50,00, z=526,13], EntitySpider['Spider'/168932, l='MpServer', x=-387,50, y=96,00, z=591,50], EntitySquid['Squid'/169188, l='MpServer', x=-370,66, y=49,37, z=529,91], EntitySquid['Squid'/169189, l='MpServer', x=-369,47, y=49,87, z=530,53], EntitySlime['Slime'/126451, l='MpServer', x=-330,78, y=13,00, z=606,78], EntityCreeper['Creeper'/169462, l='MpServer', x=-357,50, y=39,00, z=490,50], EntitySpider['Spider'/167415, l='MpServer', x=-265,50, y=73,00, z=619,50], EntityCreeper['Creeper'/169463, l='MpServer', x=-356,50, y=39,00, z=492,50], EntitySkeleton['Skeleton'/167418, l='MpServer', x=-261,50, y=75,00, z=624,06], EntityOtherPlayerMP['Rosiq'/255, l='MpServer', x=-303,59, y=73,00, z=706,72]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 564254704 bytes (538 MB) / 1213431808 bytes (1157 MB) up to 5355339776 bytes (5107 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 96
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 69 mods loaded, 69 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJA	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJA	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHIJA	CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar) 
	UCHIJA	ImmibisMicroblocks{59.1.0} [Immibis's Microblocks] (immibis-microblocks-59.1.0.jar) 
	UCHIJA	NotEnoughItems{1.0.5.111} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.111-universal.jar) 
	UCHIJA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJA	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCHIJA	BiblioCraft{1.10.4} [BiblioCraft] (BiblioCraft[v1.10.4][MC1.7.10].jar) 
	UCHIJA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1364-universal.jar) 
	UCHIJA	BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition] (BiblioWoods[BiomesOPlenty][v1.9].jar) 
	UCHIJA	ExtrabiomesXL{3.16.2} [ExtrabiomesXL] (extrabiomesxl_1.7.10-3.16.2.jar) 
	UCHIJA	BiblioWoodsEBXL{1.4} [BiblioWoods ExtraBiomesXL Edition] (BiblioWoods[ExtraBiomesXL][v1.4].jar) 
	UCHIJA	IC2{2.2.756-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.756-experimental.jar) 
	UCHIJA	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
	UCHIJA	BuildCraft|Core{7.0.16} [BuildCraft] (buildcraft-7.0.16.jar) 
	UCHIJA	Forestry{3.6.3.20} [Forestry for Minecraft] (forestry_1.7.10-3.6.3.20.jar) 
	UCHIJA	BiblioWoodsForestry{1.7} [BiblioWoods Forestry Edition] (BiblioWoods[Forestry][v1.7].jar) 
	UCHIJA	BinnieCore{2.0-pre14} [Binnie Core] (binnie-mods-2.0-pre14 (1).jar) 
	UCHIJA	Botany{2.0-pre14} [Botany] (binnie-mods-2.0-pre14 (1).jar) 
	UCHIJA	ExtraBees{2.0-pre14} [Extra Bees] (binnie-mods-2.0-pre14 (1).jar) 
	UCHIJA	ExtraTrees{2.0-pre14} [Extra Trees] (binnie-mods-2.0-pre14 (1).jar) 
	UCHIJA	Genetics{2.0-pre14} [Genetics] (binnie-mods-2.0-pre14 (1).jar) 
	UCHIJA	BuildCraft|Factory{7.0.16} [BC Factory] (buildcraft-7.0.16.jar) 
	UCHIJA	BuildCraft|Silicon{7.0.16} [BC Silicon] (buildcraft-7.0.16.jar) 
	UCHIJA	BuildCraft|Energy{7.0.16} [BC Energy] (buildcraft-7.0.16.jar) 
	UCHIJA	BuildCraft|Builders{7.0.16} [BC Builders] (buildcraft-7.0.16.jar) 
	UCHIJA	BuildCraft|Transport{7.0.16} [BC Transport] (buildcraft-7.0.16.jar) 
	UCHIJA	BuildCraft|Robotics{7.0.16} [BC Robotics] (buildcraft-7.0.16.jar) 
	UCHIJA	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
	UCHIJA	ComputerCraft{1.73} [ComputerCraft] (ComputerCraft1.73.jar) 
	UCHIJA	DragonsRadioMod{1.6.3} [Dragon's Radio Mod] (DragonsRadioMod-MC1.7.10-1.6.3.jar) 
	UCHIJA	EnderStorage{1.4.7.36} [EnderStorage] (EnderStorage-1.7.10-1.4.7.36-universal (1).jar) 
	UCHIJA	ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0-102.jar) 
	UCHIJA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJA	ExtraUtilities{1.2.8} [Extra Utilities] (extrautilities-1.2.8.jar) 
	UCHIJA	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) 
	UCHIJA	GraviSuite{1.7.10-2.0.3} [Graviation Suite] (GraviSuite-1.7.10-2.0.3.jar) 
	UCHIJA	IC2NuclearControl{2.2.5a-GoingForTheKill} [Nuclear Control 2] (IC2NuclearControl-2.2.5a-GoingForTheKill.jar) 
	UCHIJA	ImmibisCore{59.1.1} [Immibis Core] (immibis-core-59.1.1 (1).jar) 
	UCHIJA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHIJA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJA	JABBA{1.2.1} [JABBA] (Jabba-1.2.1a_1.7.10.jar) 
	UCHIJA	journeymap{@JMVERSION@} [JourneyMap] (journeymap-1.7.10-5.1.0-unlimited.jar) 
	UCHIJA	ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
	UCHIJA	LogisticsPipes{0.9.1.15} [Logistics Pipes] (logisticspipes-0.9.1.15.jar) 
	UCHIJA	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) 
	UCHIJA	NEIAddons{1.12.10.33} [NEI Addons] (neiaddons-1.12.10.33-mc1.7.10 (1).jar) 
	UCHIJA	NEIAddons|AppEng{1.12.10.33} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.10.33-mc1.7.10 (1).jar) 
	UCHIJA	NEIAddons|Botany{1.12.10.33} [NEI Addons: Botany] (neiaddons-1.12.10.33-mc1.7.10 (1).jar) 
	UCHIJA	NEIAddons|Forestry{1.12.10.33} [NEI Addons: Forestry] (neiaddons-1.12.10.33-mc1.7.10 (1).jar) 
	UCHIJA	NEIAddons|CraftingTables{1.12.10.33} [NEI Addons: Crafting Tables] (neiaddons-1.12.10.33-mc1.7.10 (1).jar) 
	UCHIJA	NEIAddons|ExNihilo{1.12.10.33} [NEI Addons: Ex Nihilo] (neiaddons-1.12.10.33-mc1.7.10 (1).jar) 
	UCHIJA	neiintegration{1.0.11} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.11 (1).jar) 
	UCHIJA	OCS{1.7.5} [OpenCCSensors] (openccsensors-1.7.5.jar) 
	UCHIJA	PneumaticCraft{1.9.2-88} [PneumaticCraft] (PneumaticCraft-1.7.10-1.9.2-88-universal.jar) 
	UCHIJA	MrTJPCoreMod{1.0.7.14} [MrTJPCore] (MrTJPCore-1.0.7.14-universal.jar) 
	UCHIJA	ProjRed|Core{4.6.1.80} [ProjectRed] (ProjectRed-1.7.10-4.6.1.80-Base.jar) 
	UCHIJA	ProjRed|Integration{4.6.1.80} [ProjectRed-Integration] (ProjectRed-1.7.10-4.6.1.80-Integration.jar) 
	UCHIJA	ProjRed|Transmission{4.6.1.80} [ProjectRed-Transmission] (ProjectRed-1.7.10-4.6.1.80-Integration.jar) 
	UCHIJA	ProjRed|Illumination{4.6.1.80} [ProjectRed-Illumination] (ProjectRed-1.7.10-4.6.1.80-Lighting.jar) 
	UCHIJA	Railcraft{9.6.1.0} [Railcraft] (Railcraft_1.7.10-9.6.1.0.jar) 
	UCHIJA	ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.1.0-161.jar) 
	UCHIJA	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJA	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJA	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 353.30' Renderer: 'GeForce GTX 770/PCIe/SSE2'
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	CoFHCore: -[1.7.10]3.0.3-303
	ThermalFoundation: -[1.7.10]1.2.0-102
	ThermalExpansion: -[1.7.10]4.0.3B1-218
	ThermalDynamics: -[1.7.10]1.1.0-161
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:ON, BC:ON, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:OFF, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Launched Version: 1.7.10-Forge10.13.4.1448-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 770/PCIe/SSE2 GL version 4.5.0 NVIDIA 353.30, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
[19:16:53] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:359]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Petr\AppData\Roaming\.minecraftBezGrega\crash-reports\crash-2015-07-23_19.16.53-client.txt
[19:16:53] [JM-svr-2/INFO] [journeymap]: Stopped webserver without errors

**Comment by MoonDroper** [comment]
@Chicken-Bones can you help me please? :(

**Comment by SquidDev** [comment]
Have a look at MrTJP/ProjectRed#823, MrTJP/ProjectRed#795 and MrTJP/ProjectRed#789. You probably want to upgrade ProjectRed to 4.7 or downgrade FMP to 1.1.2.334.
