### ISSUE TITLE
Crash when adding Project-Red Inverted Lamps to FMP config

### ISSUE THREAD

**Issue by Sandriell** [Chicken-Bones/ForgeMultipart#370]
I tried adding the Inverted Lamps to the microblocks config on my server/client and it crashes when trying to view the recipe, either in NEI or in a crafting table.

Line added: "ProjRed|Illumination:projectred.illumination.lamp":0-31

Crash Log: https://gist.github.com/Sandriell/a76e7f6d63a52e033510

Forge: 1448
ProjectRed: 4.6.2.82
FMP: 1.2.0.344

Also reported to Project-Red: https://github.com/MrTJP/ProjectRed/issues/931

**Comment by amadornes** [comment]
There aren't 32 types of lamps. Block metadata can only go from 0 to 15. Replace "0-31" with "0-15" and it should work.

**Comment by Sandriell** [comment]
The 0-31 was to cover both the inverted and regular types of lamps (0-15 for regular and 16-31 for inverted) which all share the same blockname. Granted I was only really after the Inverted style, but I figured why not just add them all.

For testing purposes though, I just went ahead and tried adding just one specific lamp:

"ProjRed|Illumination:projectred.illumination.lamp":16

Which is the white inverted lamp. Same crash.

Here is a screenshot showing the lamp I tried adding: http://i.imgur.com/GWiZolA.png

**Comment by Dream-Master** [comment]
i get some similar error.

https://gist.github.com/Dream-Master/6c4b1b1212ead7026fe9#file-crash

**Comment by Kubuxu** [comment]
Problem is that those lamps use custom ItemBlocks, they use Item metadata, which can go to 2^16-1, and in world properties are remembered under one metadata (0) and tile entity data.

**Comment by Dream-Master** [comment]
@Kubuxu 
is there a way to disabled blocks from multipart. I see only many tutorials how to adding new ones.

**Comment by Kubuxu** [comment]
No idea.

**Comment by Dream-Master** [comment]
InpureCore only hiding Blocks but not delete them.

**Comment by MrTJP** [comment]
As of the latest version, the inverted lamp microblocks are added automatically. They also glow when placed in-world. The standard configs can be used to add the non-inverted lamps as micro blocks (if you would want to do such a thing).

This is no longer an issue.

**Comment by aard2** [comment]
@MrTJP I am crashing when trying to harvest inverted lamp microblocks - crash log below:

[30/7/2016 07:49:07 AM] java.lang.ArrayIndexOutOfBoundsException: 16
[30/7/2016 07:49:07 AM] 	at net.minecraft.block.Block.isToolEffective(Block.java:2226)
[30/7/2016 07:49:07 AM] 	at net.minecraftforge.common.ForgeHooks.isToolEffective(ForgeHooks.java:146)
[30/7/2016 07:49:07 AM] 	at net.minecraft.item.ItemTool.getDigSpeed(ItemTool.java:128)
[30/7/2016 07:49:07 AM] 	at net.minecraft.entity.player.EntityPlayer.getBreakSpeed(EntityPlayer.java:811)
[30/7/2016 07:49:07 AM] 	at codechicken.microblock.BlockMicroMaterial.getStrength(BlockMicroMaterial.scala:98)
[30/7/2016 07:49:07 AM] 	at codechicken.microblock.Microblock.getStrength(Microblock.scala:44)
[30/7/2016 07:49:07 AM] 	at codechicken.multipart.BlockMultipart.func_149737_a(BlockMultipart.scala:205)
[30/7/2016 07:49:07 AM] 	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78743_b(PlayerControllerMP.java:177)
[30/7/2016 07:49:07 AM] 	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1409)
[30/7/2016 07:49:07 AM] 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1948)
[30/7/2016 07:49:07 AM] 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
[30/7/2016 07:49:07 AM] 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
[30/7/2016 07:49:07 AM] 	at net.minecraft.client.main.Main.main(SourceFile:148)
[30/7/2016 07:49:07 AM] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[30/7/2016 07:49:07 AM] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[30/7/2016 07:49:07 AM] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[30/7/2016 07:49:07 AM] 	at java.lang.reflect.Method.invoke(Unknown Source)
[30/7/2016 07:49:07 AM] 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[30/7/2016 07:49:07 AM] 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
