### ISSUE TITLE
Mekanism Cable crash

### ISSUE THREAD

**Issue by Akeginu** [Chicken-Bones/ForgeMultipart#383]
aidancbrady told me to put this on here

-- Minecraft Crash Report ----
// Daisy, daisy...

Time: 24.05.2016 19:58
Description: Ticking memory connection

java.util.NoSuchElementException: None.get
    at scala.None$.get(Option.scala:322)
    at scala.None$.get(Option.scala:320)
    at codechicken.multipart.MultiPartRegistry$.writePartID(MultiPartRegistry.scala:191)
    at codechicken.multipart.TileMultipart.writeAddPart(TileMultipart.scala:289)
    at codechicken.multipart.TileMultipart.addPart_impl(TileMultipart.scala:275)
    at codechicken.multipart.MultipartGenerator$.addPart(MultipartGenerator.scala:97)
    at codechicken.multipart.TileMultipart$.addPart(TileMultipart.scala:601)
    at codechicken.multipart.TItemMultiPart$class.place$1(ItemMultiPart.scala:37)
    at codechicken.multipart.TItemMultiPart$class.onItemUse(ItemMultiPart.scala:47)
    at codechicken.multipart.JItemMultiPart.func_77648_a(ItemMultiPart.scala:14)
    at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505)
    at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:128)
    at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:389)
    at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at scala.None$.get(Option.scala:322)
    at scala.None$.get(Option.scala:320)
    at codechicken.multipart.MultiPartRegistry$.writePartID(MultiPartRegistry.scala:191)
    at codechicken.multipart.TileMultipart.writeAddPart(TileMultipart.scala:289)
    at codechicken.multipart.TileMultipart.addPart_impl(TileMultipart.scala:275)
    at codechicken.multipart.MultipartGenerator$.addPart(MultipartGenerator.scala:97)
    at codechicken.multipart.TileMultipart$.addPart(TileMultipart.scala:601)
    at codechicken.multipart.TItemMultiPart$class.place$1(ItemMultiPart.scala:37)
    at codechicken.multipart.TItemMultiPart$class.onItemUse(ItemMultiPart.scala:47)
    at codechicken.multipart.JItemMultiPart.func_77648_a(ItemMultiPart.scala:14)
    at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505)
    at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:128)
    at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:389)
    at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
    Connection: net.minecraft.network.NetworkManager@1f2e163
Stacktrace:
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (x86) version 6.1
    Java Version: 1.8.0_51, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 129205432 bytes (123 MB) / 466944000 bytes (445 MB) up to 1216348160 bytes (1160 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1200M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 Optifine OptiFine_1.7.10_HD_U_C1 11 mods loaded, 11 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1558-1.7.10.jar) 
    UCHIJAAAA   Forge{10.13.4.1558} [Minecraft Forge](forge-1.7.10-10.13.4.1558-1.7.10.jar) 
    UCHIJAAAA   CodeChickenCore{1.0.4.29} [CodeChicken Core](minecraft.jar) 
    UCHIJAAAA   NotEnoughItems{1.0.4.83} [Not Enough Items](NotEnoughItems-1.7.10-1.0.4.83-universal.jar) 
    UCHIJAAAA   ForgeMultipart{1.1.2.331} [Forge Multipart](ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
    UCHIJAAAA   Mekanism{9.0.0} [Mekanism](Mekanism-1.7.10-9.0.0.269.jar) 
    UCHIJAAAA   MekanismGenerators{9.0.0} [MekanismGenerators](MekanismGenerators-1.7.10-9.0.0.269.jar) 
    UCHIJAAAA   MekanismTools{9.0.0} [MekanismTools](MekanismTools-1.7.10-9.0.0.269.jar) 
    UCHIJAAAA   McMultipart{1.1.2.331} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
    UCHIJAAAA   ForgeMicroblock{1.1.2.331} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['Akeginu'/602, l='World thingy', x=-154,71, y=65,30, z=769,55]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Akeginu** [comment]
If someone could help I would really appriciate
