### ISSUE TITLE
Server Keeps crashing

### ISSUE THREAD

**Issue by bentschwarz** [Chicken-Bones/ForgeMultipart#387]
I've been playing on this server for months now which i host myself and everything was going fine but i accidentally turned my computer off while it was running and now i get this error...Does anyone know how to help?

---- Minecraft Crash Report ----
// My bad.

Time: 2/2/17 3:26 PM
Description: Exception in server tick loop

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1
	at com.google.gson.Gson.fromJson(Gson.java:815)
	at com.google.gson.Gson.fromJson(Gson.java:768)
	at net.minecraft.server.management.UserList.func_152679_g(SourceFile:125)
	at net.minecraft.server.dedicated.DedicatedPlayerList.func_152620_y(SourceFile:99)
	at net.minecraft.server.dedicated.DedicatedPlayerList.<init>(SourceFile:25)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:211)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1
	at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:338)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:79)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:60)
	at com.google.gson.Gson.fromJson(Gson.java:803)
	... 7 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 522095008 bytes (497 MB) / 1351376896 bytes (1288 MB) up to 4242669568 bytes (4046 MB)
	JVM Flags: 2 total; -Xincgc -Xmx4096M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492 120 mods loaded, 120 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1492-1.7.10-universal.jar) 
	UCHIJA	Forge{10.13.4.1492} [Minecraft Forge] (forge-1.7.10-10.13.4.1492-1.7.10-universal.jar) 
	UCHIJA	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHIJA	CodeChickenCore{1.0.6.43} [CodeChicken Core] (minecraft.jar) 
	UCHIJA	NotEnoughItems{1.0.3.74} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.74-universal.jar) 
	UCHIJA	OpenModsCore{0.8} [OpenModsCore] (minecraft.jar) 
	UCHIJA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJA	debug{1.0} [debug] (denseores-1.6.2.jar) 
	UCHIJA	securitycraft{v1.7.4.1} [SecurityCraft] ([1.7.10] SecurityCraft v1.7.4.1.jar) 
	UCHIJA	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
	UCHIJA	BuildCraft|Core{7.0.19} [BuildCraft] (buildcraft-7.0.19.jar) 
	UCHIJA	BuildCraft|Silicon{7.0.19} [BC Silicon] (buildcraft-7.0.19.jar) 
	UCHIJA	BuildCraft|Transport{7.0.19} [BC Transport] (buildcraft-7.0.19.jar) 
	UCHIJA	BuildCraft|Factory{7.0.19} [BC Factory] (buildcraft-7.0.19.jar) 
	UCHIJA	additionalpipes{4.6.0} [Additional Pipes] (additionalpipes-4.6.1.jar) 
	UCHIJA	IC2{2.2.767-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.767-experimental (1).jar) 
	UCHIJA	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (AdvancedSolarPanel-1.7.10-3.5.1.jar) 
	UCHIJA	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UCHIJA	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCHIJA	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) 
	UCHIJA	bdlib{1.9.0.94} [BD Lib] (bdlib-1.9.0.94-mc1.7.10.jar) 
	UCHIJA	ThermalFoundation{1.7.10R1.0.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0-81.jar) 
	UCHIJA	ThermalExpansion{1.7.10R4.0.1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.1-182.jar) 
	UCHIJA	BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) 
	UCHIJA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1067-universal.jar) 
	UCHIJA	Forestry{3.6.3.20} [Forestry for Minecraft] (forestry_1.7.10-3.6.3.20.jar) 
	UCHIJA	BinnieCore{2.0-pre14} [Binnie Core] (binnie-mods-2.0-pre14.jar) 
	UCHIJA	Botany{2.0-pre14} [Botany] (binnie-mods-2.0-pre14.jar) 
	UCHIJA	ExtraBees{2.0-pre14} [Extra Bees] (binnie-mods-2.0-pre14.jar) 
	UCHIJA	ExtraTrees{2.0-pre14} [Extra Trees] (binnie-mods-2.0-pre14.jar) 
	UCHIJA	Genetics{2.0-pre14} [Genetics] (binnie-mods-2.0-pre14.jar) 
	UCHIJA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHIJA	Botania{r1.7-208} [Botania] (Botania r1.7-208.jar) 
	UCHIJA	BuildCraft|Builders{7.0.19} [BC Builders] (buildcraft-7.0.19.jar) 
	UCHIJA	BuildCraft|Robotics{7.0.19} [BC Robotics] (buildcraft-7.0.19.jar) 
	UCHIJA	BuildCraft|Energy{7.0.19} [BC Energy] (buildcraft-7.0.19.jar) 
	UCHIJA	BuildCraft|Compat{7.0.8} [BuildCraft Compat] (buildcraft-compat-7.0.8.jar) 
	UCHIJA	CarpentersBlocks{3.3.6} [Carpenter's Blocks] (Carpenter's Blocks v3.3.6 - MC 1.7.10.jar) 
	UCHIJA	ChickenChunks{1.3.4.16} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.16-universal.jar) 
	UCHIJA	Railcraft{9.6.1.0} [Railcraft] (Railcraft_1.7.10-9.6.1.0.jar) 
	UCHIJA	TwilightForest{2.3.2} [The Twilight Forest] (twilightforest-1.7.10-2.3.2.jar) 
	UCHIJA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJA	chisel{2.4.1.40} [Chisel 2] (Chisel2-2.4.1.40.jar) 
	UCHIJA	ctmlib{1.0.1.5} [CTMLib] (Chisel2-2.4.1.40.jar) 
	UCHIJA	ComputerCraft{1.73} [ComputerCraft] (ComputerCraft1.73.jar) 
	UCHIJA	props{2.0.2} [Decocraft] (Decocraft-2.0.2_1.7.10.jar) 
	UCHIJA	endercore{1.7.10-0.1.0.23_beta} [EnderCore] (EnderCore-1.7.10-0.1.0.23_beta.jar) 
	UCHIJA	MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	EnderIO{1.7.10-2.3.0.413_beta} [Ender IO] (EnderIO-1.7.10-2.3.0.413_beta.jar) 
	UCHIJA	EnderStorage{1.4.7.33} [EnderStorage] (EnderStorage-1.7.10-1.4.7.33-universal.jar) 
	UCHIJA	extracells{2.2.64} [ExtraCells] (ExtraCells-1.7.10-2.2.64b96.jar) 
	UCHIJA	ExtraUtilities{1.2.11} [Extra Utilities] (extrautilities-1.2.11.jar) 
	UCHIJA	fastleafdecay{1.1} [Fast Leaf Decay] (FastLeafDecay-1.7.10-1.1.jar) 
	UCHIJA	gendustry{1.5.2.107} [GenDustry] (gendustry-1.5.2.107-mc1.7.10.jar) 
	UCHIJA	GraviSuite{1.7.10-2.0.3} [Graviation Suite] (GraviSuite-1.7.10-2.0.3.jar) 
	UCHIJA	IC2NuclearControl{2.1.2a} [Nuclear Control 2] (IC2NuclearControl-2.1.2a.jar) 
	UCHIJA	iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar) 
	UCHIJA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHIJA	JABBA{1.2.1} [JABBA] (Jabba-1.2.1a_1.7.10.jar) 
	UCHIJA	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
	UCHIJA	mcheli{0.9.3} [MC Helicopter] (mcheli) 
	UCHIJA	mm{1.7.10-1.1} [Minecraft Money] (MinecraftMoney-1.7.10-1.2-01.jar) 
	UCHIJA	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MrTJPCoreMod{1.1.0.31} [MrTJPCore] (MrTJPCore-1.7.10-1.1.0.31-universal.jar) 
	UCHIJA	ProjRed|Core{4.7.0pre8.92} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre8.92-Base.jar) 
	UCHIJA	ProjRed|Exploration{4.7.0pre8.92} [ProjectRed Exploration] (ProjectRed-1.7.10-4.7.0pre8.92-World.jar) 
	UCHIJA	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	TConstruct{1.7.10-1.8.5.build957} [Tinkers' Construct] (TConstruct-1.7.10-1.8.5.jar) 
	UCHIJA	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	NetherOres{1.7.10R2.3.0} [Nether Ores] (NetherOres-[1.7.10]2.3.0-12.jar) 
	UCHIJA	OpenMods{0.8} [OpenMods] (OpenModsLib-1.7.10-0.8.jar) 
	UCHIJA	OpenBlocks{1.4.4} [OpenBlocks] (OpenBlocks-1.7.10-1.4.4.jar) 
	UCHIJA	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10j.jar) 
	UCHIJA	PneumaticCraft{1.5.3 - err} [PneumaticCraft] (PneumaticCraft-1.7.10-1.5.3-universal.jar) 
	UCHIJA	PowerConverters3{1.7.10-2.10} [Power Converters 3] (PowerConverters-1.7.10-2.10.jar) 
	UCHIJA	progressiveautomation{1.6.27} [Progressive Automation] (ProgressiveAutomation-1.7.10-1.6.27.jar) 
	UCHIJA	ProjRed|Transmission{4.7.0pre8.92} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre8.92-Integration.jar) 
	UCHIJA	ProjRed|Transportation{4.7.0pre8.92} [ProjectRed Transportation] (ProjectRed-1.7.10-4.7.0pre8.92-Mechanical.jar) 
	UCHIJA	ProjRed|Compatibility{4.7.0pre8.92} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre8.92-Compat.jar) 
	UCHIJA	ProjRed|Integration{4.7.0pre8.92} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre8.92-Integration.jar) 
	UCHIJA	ProjRed|Fabrication{4.7.0pre8.92} [ProjectRed Fabrication] (ProjectRed-1.7.10-4.7.0pre8.92-Fabrication.jar) 
	UCHIJA	ProjRed|Illumination{4.7.0pre8.92} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre8.92-Lighting.jar) 
	UCHIJA	ProjRed|Expansion{4.7.0pre8.92} [ProjectRed Expansion] (ProjectRed-1.7.10-4.7.0pre8.92-Mechanical.jar) 
	UCHIJA	RedstoneArsenal{1.7.10R1.1.1} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.1-89.jar) 
	UCHIJA	SolarExpansion{1.6a} [Solar Expansion] (SolarExpansion-Basic-1.6a.jar) 
	UCHIJA	StevesFactoryManager{A93} [Steve's Factory Manager] (StevesFactoryManagerA93.jar) 
	UCHIJA	StevesAddons{0.10.16} [Steve's Addons] (StevesAddons-1.7.10-0.10.16.jar) 
	UCHIJA	StevesCarts{2.0.0.b18} [Steve's Carts 2] (StevesCarts2.0.0.b18.jar) 
	UCHIJA	StevesWorkshop{0.5.1} [Steve's Workshop] (StevesWorkshop-0.5.1.jar) 
	UCHIJA	ThermalCasting{0.0.1} [Thermal Casting] (thermalcasting-0.0.2.jar) 
	UCHIJA	ThermalDynamics{1.7.10R1.0.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.0.0-122.jar) 
	UCHIJA	TiCTooltips{1.2.3} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.3.jar) 
	UCHIJA	TMechworks{1.7.10-86.e500b88} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.10.jar) 
	UCHIJA	WR-CBE|Core{1.4.1.7} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.7-universal.jar) 
	UCHIJA	WR-CBE|Addons{1.4.1.7} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.7-universal.jar) 
	UCHIJA	WR-CBE|Logic{1.4.1.7} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.7-universal.jar) 
	UCHIJA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJA	ForgeRelocation{0.0.1.3} [ForgeRelocation] (ForgeRelocation-1.7.10-0.0.1.3-universal.jar) 
	UCHIJA	MCFrames{1.0} [MCFrames] (ForgeRelocation-1.7.10-0.0.1.3-universal.jar) 
	UCHIJA	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar) 
	UCHIJA	denseores{1.0} [Dense Ores] (denseores-1.6.2.jar) 
	UCHIJA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	OpenModsLib class transformers: [stencil_patches:ENABLED],[movement_callback:ENABLED],[map_gen_fix:FINISHED],[gl_capabilities_hook:ENABLED],[player_render_hook:ENABLED]
	Class transformer null safety: all safe
	CoFHCore: -[1.7.10]3.0.3-303
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	ThermalFoundation: -[1.7.10]1.0.0-81
	ThermalExpansion: -[1.7.10]4.0.1-182
	MineFactoryReloaded: -[1.7.10]2.8.0-104
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	NetherOres: -[1.7.10]2.3.0-12
	RedstoneArsenal: -[1.7.10]1.1.1-89
	ThermalDynamics: -[1.7.10]1.0.0-122
	List of loaded APIs: 
		* apAPI (1) from additionalpipes-4.6.1.jar
		* appliedenergistics2|API (rv2) from appliedenergistics2-rv2-stable-10.jar
		* Baubles|API (1.0.1.10) from Baubles-1.7.10-1.0.1.10.jar
		* BiomesOPlentyAPI (1.0.0) from BiomesOPlenty-1.7.10-2.1.0.1067-universal.jar
		* BotaniaAPI (58) from Botania r1.7-208.jar
		* BuildCraftAPI|blocks (1.0) from buildcraft-7.0.19.jar
		* BuildCraftAPI|blueprints (1.3) from buildcraft-7.0.19.jar
		* BuildCraftAPI|boards (2.0) from buildcraft-7.0.19.jar
		* BuildCraftAPI|core (1.4) from Railcraft_1.7.10-9.6.1.0.jar
		* BuildCraftAPI|crops (1.1) from buildcraft-7.0.19.jar
		* BuildCraftAPI|events (1.0) from buildcraft-7.0.19.jar
		* BuildCraftAPI|facades (1.1) from buildcraft-7.0.19.jar
		* BuildCraftAPI|filler (4.0) from buildcraft-7.0.19.jar
		* BuildCraftAPI|fuels (2.0) from buildcraft-7.0.19.jar
		* BuildCraftAPI|gates (4.1) from buildcraft-7.0.19.jar
		* BuildCraftAPI|items (1.0) from Railcraft_1.7.10-9.6.1.0.jar
		* BuildCraftAPI|library (2.0) from buildcraft-7.0.19.jar
		* BuildCraftAPI|power (1.3) from buildcraft-7.0.19.jar
		* BuildCraftAPI|recipes (3.0) from buildcraft-7.0.19.jar
		* BuildCraftAPI|robotics (2.1) from buildcraft-7.0.19.jar
		* BuildCraftAPI|statements (1.1) from buildcraft-7.0.19.jar
		* BuildCraftAPI|tablet (1.0) from buildcraft-7.0.19.jar
		* BuildCraftAPI|tiles (1.1) from Railcraft_1.7.10-9.6.1.0.jar
		* BuildCraftAPI|tools (1.0) from SolarExpansion-Basic-1.6a.jar
		* BuildCraftAPI|transport (4.0) from Railcraft_1.7.10-9.6.1.0.jar
		* ChiselAPI (0.1.0) from Chisel2-2.4.1.40.jar
		* ChiselAPI|Carving (0.1.0) from Chisel2-2.4.1.40.jar
		* ChiselAPI|Rendering (0.1.0) from Chisel2-2.4.1.40.jar
		* CoFHAPI (1.7.10R1.0.2) from forestry_1.7.10-3.6.3.20.jar
		* CoFHAPI|block (1.7.10R1.0.3) from SolarExpansion-Basic-1.6a.jar
		* CoFHAPI|core (1.7.10R1.0.3) from SolarExpansion-Basic-1.6a.jar
		* CoFHAPI|energy (1.7.10R1.0.3) from SolarExpansion-Basic-1.6a.jar
		* CoFHAPI|fluid (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHAPI|inventory (1.7.10R1.0.12) from EnderIO-1.7.10-2.3.0.413_beta.jar
		* CoFHAPI|item (1.7.10R1.0.12) from EnderIO-1.7.10-2.3.0.413_beta.jar
		* CoFHAPI|items (1.7.10R1.0.3) from SolarExpansion-Basic-1.6a.jar
		* CoFHAPI|modhelpers (1.7.10R1.0.3) from SolarExpansion-Basic-1.6a.jar
		* CoFHAPI|tileentity (1.7.10R1.0.13) from ProgressiveAutomation-1.7.10-1.6.27.jar
		* CoFHAPI|transport (1.7.10R1.0.1) from buildcraft-compat-7.0.8.jar
		* CoFHAPI|world (1.7.10R1.0.3) from SolarExpansion-Basic-1.6a.jar
		* CoFHLib (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|audio (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|gui (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|gui|container (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|gui|element (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|gui|element|listbox (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|gui|slot (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|inventory (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|render (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|render|particle (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|util (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|util|helpers (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|util|position (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|world (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|world|feature (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* ComputerCraft|API (1.73) from ComputerCraft1.73.jar
		* ComputerCraft|API|FileSystem (1.73) from ComputerCraft1.73.jar
		* ComputerCraft|API|Lua (1.73) from ComputerCraft1.73.jar
		* ComputerCraft|API|Media (1.73) from ComputerCraft1.73.jar
		* ComputerCraft|API|Peripheral (1.73) from ComputerCraft1.73.jar
		* ComputerCraft|API|Redstone (1.73) from ComputerCraft1.73.jar
		* ComputerCraft|API|Turtle (1.73) from ComputerCraft1.73.jar
		* CSLib|API (1.0) from Decocraft-2.0.2_1.7.10.jar
		* EnderIOAPI (0.0.2) from EnderIO-1.7.10-2.3.0.413_beta.jar
		* EnderIOAPI|Redstone (0.0.2) from EnderIO-1.7.10-2.3.0.413_beta.jar
		* EnderIOAPI|Teleport (0.0.2) from EnderIO-1.7.10-2.3.0.413_beta.jar
		* EnderIOAPI|Tools (0.0.2) from EnderIO-1.7.10-2.3.0.413_beta.jar
		* ForestryAPI|apiculture (3.5.0) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|arboriculture (2.3.0) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|circuits (2.0.0) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|core (3.2.0) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|farming (1.1.0) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|food (1.1.0) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|fuels (2.0.1) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|genetics (3.3.0) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|lepidopterology (1.1) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|mail (3.0.0) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|recipes (3.1.0) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|storage (3.0.0) from forestry_1.7.10-3.6.3.20.jar
		* ForestryAPI|world (1.1.0) from forestry_1.7.10-3.6.3.20.jar
		* ForgeRelocation|API (0.0.1.3) from ForgeRelocation-1.7.10-0.0.1.3-universal.jar
		* gendustryAPI (2.1.0) from gendustry-1.5.2.107-mc1.7.10.jar
		* IC2API (1.0) from industrialcraft-2-2.2.767-experimental (1).jar
		* NuclearControlAPI (v1.0.5) from IC2NuclearControl-2.1.2a.jar
		* OpenBlocks|API (1.0) from OpenBlocks-1.7.10-1.4.4.jar
		* PneumaticCraftApi (1.0) from PneumaticCraft-1.7.10-1.5.3-universal.jar
		* RailcraftAPI|bore (1.0.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|carts (1.3.1) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|core (1.3.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|crafting (1.0.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|electricity (1.6.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|events (1.0.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|fuel (1.0.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|helpers (1.1.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|items (1.0.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|locomotive (1.0.1) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|signals (1.3.0) from Railcraft_1.7.10-9.6.1.0.jar
		* RailcraftAPI|tracks (2.0.0) from Railcraft_1.7.10-9.6.1.0.jar
		* Thaumcraft|API (4.2.0.0) from Pam's HarvestCraft 1.7.10j.jar
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:ON, BC:ON, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by simon816** [comment]
Your `banned-players.json` file is corrupt. You need to fix the invalid JSON or delete it.
Since the server unexpectedly shutdown I highly recommend restoring from a backup since there could have been some corruption elsewhere too
